[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 800       # gộp vào 1 dòng duy nhất
via_ir = false              # bật via-ir để tránh "stack too deep"

solc_version = "0.8.26"
evm_version = "cancun"

ffi = true
